name = "Vanilla Season 6"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e667233c37c4ddfdf98f2ca8968387402b0fa92bef257bc638421d8524bc83e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
