name = "Vanilla Season 6"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dca19125362196e05d354217adff8399ac8193ba6694b114bc96fac1df612231"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
