name = "Дэбилы: Create Aeronautics"
author = "vlasovich"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a415612448ad4c3fa3c50ff3994378f3f8f6b6b369d7cd419862eb6e7846a75f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
